version: '3'
services:
  app:
    container_name: go-server
    build: .
    ports:
      - "8080:8080"
  python:
    hostname: pyserver
    container_name: python-nn
    build: ./docker/python
    ports:
      - "8000:8000"